version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: us
      POSTGRES_PASSWORD: test
      POSTGRES_DB: gymmy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: