version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: us
      POSTGRES_PASSWORD: test
      POSTGRES_DB: gymmy
    volumes:
      - postgres_data:/var/lib/postgresql/data
  gummy-app:
    build: .
    container_name: gummy-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gymmy
      SPRING_DATASOURCE_USERNAME: us
      SPRING_DATASOURCE_PASSWORD: test
      APP_HOST: http://localhost:8080
    depends_on:
      - postgres

volumes:
  postgres_data: