spring:
  application:
    name: gymmy
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 7pvp2a8btqcvgq9e5mplql11ps
            clientSecret: d4u2sa45h5dbslgcas33cs9ur25jago2u8o4lpmoc5pdgri896e
#            scope: openid
            redirect-uri: https://u0eishcald.execute-api.eu-central-1.amazonaws.com/login/oauth2/code/cognito
            clientName: gummy-app
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/${aws.poolId}
server:
  servlet:
    session:
      timeout: 30m

aws:
  poolId: eu-central-1_Gn0iqXCjK
  s3:
    bucketName: test-gummu-user-images
    accessKey: AKIA6GBMC5FOWRDKQ7A2
    secretKey: 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